WINDOW_WIDTH, WINDOW_HEIGHT = love.window.getDesktopDimensions()

VIRTUAL_WIDTH = 4484
VIRTUAL_HEIGHT = 2416

PLAYER_WALK_SPEED = 900

GRAVITY_AMOUNT = 60

PLAYER_JUMP_VELOCITY = -1500

MAP_WIDTH = math.floor(VIRTUAL_WIDTH)
MAP_HEIGHT = math.floor(VIRTUAL_HEIGHT)

MAP_RENDER_OFFSET_X = (VIRTUAL_WIDTH - MAP_WIDTH) / 2
MAP_RENDER_OFFSET_Y = (VIRTUAL_HEIGHT - MAP_HEIGHT) / 2