VIRTUAL_WIDTH = 384
VIRTUAL_HEIGHT = 216

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

PLAYER_WALK_SPEED = 100

MAP_WIDTH = math.floor(VIRTUAL_WIDTH)
MAP_HEIGHT = math.floor(VIRTUAL_HEIGHT)

MAP_RENDER_OFFSET_X = (VIRTUAL_WIDTH - MAP_WIDTH) / 2
MAP_RENDER_OFFSET_Y = (VIRTUAL_HEIGHT - MAP_HEIGHT) / 2