WINDOW_WIDTH, WINDOW_HEIGHT = love.window.getDesktopDimensions()

VIRTUAL_WIDTH = 1920
VIRTUAL_HEIGHT = 1080

GRAVITY_AMOUNT = 60

MAP_WIDTH = math.floor(VIRTUAL_WIDTH)
MAP_HEIGHT = math.floor(VIRTUAL_HEIGHT)

MAP_RENDER_OFFSET_X = (VIRTUAL_WIDTH - MAP_WIDTH) / 2
MAP_RENDER_OFFSET_Y = (VIRTUAL_HEIGHT - MAP_HEIGHT) / 2